-- ============================================================================
-- APEX Values & Wiki — Supabase schema (security-hardened revision)
-- Project: https://rfeoicbcprziqlcmbjgi.supabase.co
--
-- What changed vs the previous version:
--   1. ADMIN ROLE HELPERS: is_owner(), is_admin(), is_value_editor(),
--      is_wiki_editor(), is_fanart_editor(), current_admin_role() — all SECURITY DEFINER so they
--      work inside RLS policies and views.
--   2. EMAIL PRIVACY (real fix, not UI-only): the change-log tables no longer
--      leak changed_by_email to the public. A set of *_public VIEWS mask the
--      email column unless the requester is owner/admin. The base tables are
--      not readable by anon at all.
--   3. ACCOUNTABILITY: BEFORE INSERT triggers force changed_by_email and
--      changed_by to the REAL authenticated user, ignoring whatever the client
--      sent — so an editor can't frame another editor.
--   4. Fixed the SQL syntax bug (missing comma) that aborted the whole
--      admin_users seed.
--   5. Full 7-member team roles.
--   6. Added fanart_entries table and bug_reports table for community features.
--   7. Added fanart_editor role and permission helpers.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
create table if not exists public.admin_users (
  email text primary key,
  role text not null default 'wiki_editor',
  created_at timestamptz not null default now()
);

alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users add constraint admin_users_role_check
  check (role in ('owner', 'admin', 'value_editor', 'wiki_editor', 'fanart_editor', 'editor'));

create table if not exists public.value_entries (
  slug text primary key,
  kind text not null default 'unit',
  base_value numeric not null default 1,
  gems numeric not null default 1,
  coins numeric not null default 1,
  demand text not null default 'Normal',
  scarcity text not null default 'Standard',
  trend text not null default 'stable',
  notes text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.value_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  kind text not null default 'unit',
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

create table if not exists public.unit_wiki_overrides (
  slug text primary key,
  name text,
  rarity text,
  custom_unit boolean not null default false,
  image_url text,
  description text,
  type text,
  raw_type text,
  category text,
  placement_limit text,
  total_cost text,
  early_game_rank numeric,
  late_game_rank numeric,
  obtain jsonb,
  passive text,
  ability text,
  synergy text,
  min_max_stats jsonb,
  upgrades jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.wiki_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

-- Additive columns (idempotent).
alter table public.value_change_log add column if not exists changed_by_email text;
alter table public.wiki_change_log add column if not exists changed_by_email text;
alter table public.unit_wiki_overrides add column if not exists name text;
alter table public.unit_wiki_overrides add column if not exists rarity text;
alter table public.unit_wiki_overrides add column if not exists custom_unit boolean not null default false;
alter table public.unit_wiki_overrides add column if not exists early_game_rank numeric;
alter table public.unit_wiki_overrides add column if not exists late_game_rank numeric;

-- ============================================================================
-- FanArt Entries
-- ============================================================================
create table if not exists public.fanart_entries (
  id bigint generated by default as identity primary key,
  title text not null,
  artist_name text not null,
  image_url text not null,
  description text,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

-- ============================================================================
-- Bug Reports
-- ============================================================================
create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text not null,
  page_url text,
  contact text,
  browser text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Team roles (all 7 members). Fixed missing comma that aborted the insert.
-- ---------------------------------------------------------------------------
insert into public.admin_users (email, role) values
  ('gustavo.rb1410@gmail.com', 'owner'),
  ('bananatempest25@gmail.com', 'editor'),
  ('destroyha3@gmail.com', 'value_editor'),
  ('hellfiregamingytt@gmail.com', 'value_editor'),
  ('hungryaistukas@gmail.com', 'value_editor'),
  ('luquitas290414@gmail.com', 'wiki_editor'),
  ('treymurphy3rd@gmail.com', 'value_editor')
on conflict (email) do update set role = excluded.role;

-- ---------------------------------------------------------------------------
-- Admin role helpers (SECURITY DEFINER so they're callable in policies/views)
-- ---------------------------------------------------------------------------
create or replace function public.current_admin_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select au.role
  from public.admin_users au
  where lower(au.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1;
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin');
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() is not null;
$$;

create or replace function public.is_value_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin', 'value_editor', 'editor');
$$;

create or replace function public.is_wiki_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin', 'wiki_editor', 'editor');
$$;

create or replace function public.is_fanart_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin', 'fanart_editor', 'editor');
$$;

-- ---------------------------------------------------------------------------
-- Accountability triggers: force log authorship to the REAL authenticated user
-- ---------------------------------------------------------------------------
create or replace function public.enforce_change_log_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Always stamp the real author, ignoring any client-supplied value.
  NEW.changed_by := auth.uid();
  NEW.changed_by_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  return NEW;
end;
$$;

drop trigger if exists trg_value_log_author on public.value_change_log;
create trigger trg_value_log_author
before insert on public.value_change_log
for each row execute function public.enforce_change_log_author();

drop trigger if exists trg_wiki_log_author on public.wiki_change_log;
create trigger trg_wiki_log_author
before insert on public.wiki_change_log
for each row execute function public.enforce_change_log_author();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table public.admin_users enable row level security;
alter table public.value_entries enable row level security;
alter table public.value_change_log enable row level security;
alter table public.unit_wiki_overrides enable row level security;
alter table public.wiki_change_log enable row level security;

-- admin_users: a logged-in user can read their OWN row only.
drop policy if exists "read own admin role" on public.admin_users;
create policy "read own admin role"
on public.admin_users
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- value_entries: public read; editors write.
drop policy if exists "public read values" on public.value_entries;
create policy "public read values"
on public.value_entries
for select
to anon, authenticated
using (true);

drop policy if exists "editors insert values" on public.value_entries;
create policy "editors insert values"
on public.value_entries
for insert
to authenticated
with check (public.is_value_editor());

drop policy if exists "editors update values" on public.value_entries;
create policy "editors update values"
on public.value_entries
for update
to authenticated
using (public.is_value_editor())
with check (public.is_value_editor());

drop policy if exists "editors delete values" on public.value_entries;
create policy "editors delete values"
on public.value_entries
for delete
to authenticated
using (public.is_value_editor());

-- value_change_log: base table is ADMIN-ONLY (no anon, no public). The masked
-- *_public view below is what clients read.
drop policy if exists "public read value logs" on public.value_change_log;
create policy "admins read value logs"
on public.value_change_log
for select
to authenticated
using (public.is_admin());

drop policy if exists "editors insert value logs" on public.value_change_log;
create policy "editors insert value logs"
on public.value_change_log
for insert
to authenticated
with check (public.is_value_editor());

-- unit_wiki_overrides: public read; wiki editors write.
drop policy if exists "public read wiki overrides" on public.unit_wiki_overrides;
create policy "public read wiki overrides"
on public.unit_wiki_overrides
for select
to anon, authenticated
using (true);

drop policy if exists "wiki editors insert overrides" on public.unit_wiki_overrides;
create policy "wiki editors insert overrides"
on public.unit_wiki_overrides
for insert
to authenticated
with check (public.is_wiki_editor());

drop policy if exists "wiki editors update overrides" on public.unit_wiki_overrides;
create policy "wiki editors update overrides"
on public.unit_wiki_overrides
for update
to authenticated
using (public.is_wiki_editor())
with check (public.is_wiki_editor());

drop policy if exists "wiki editors delete overrides" on public.unit_wiki_overrides;
create policy "wiki editors delete overrides"
on public.unit_wiki_overrides
for delete
to authenticated
using (public.is_wiki_editor());

-- wiki_change_log: ADMIN-ONLY base table.
drop policy if exists "public read wiki logs" on public.wiki_change_log;
create policy "admins read wiki logs"
on public.wiki_change_log
for select
to authenticated
using (public.is_admin());

drop policy if exists "wiki editors insert logs" on public.wiki_change_log;
create policy "wiki editors insert logs"
on public.wiki_change_log
for insert
to authenticated
with check (public.is_wiki_editor());

-- ============================================================================
-- FanArt Entries Policies
-- ============================================================================
alter table public.fanart_entries enable row level security;

-- Public can read approved fanart
drop policy if exists "public read approved fanart" on public.fanart_entries;
create policy "public read approved fanart"
on public.fanart_entries
for select
to anon, authenticated
using (approved = true);

-- Fanart editors can read all fanart (for management)
drop policy if exists "fanart editors read all fanart" on public.fanart_entries;
create policy "fanart editors read all fanart"
on public.fanart_entries
for select
to authenticated
using (public.is_fanart_editor());

-- Fanart editors can insert approved fanart
drop policy if exists "fanart editors insert fanart" on public.fanart_entries;
create policy "fanart editors insert fanart"
on public.fanart_entries
for insert
to authenticated
with check (public.is_fanart_editor());

-- Fanart editors can update fanart
drop policy if exists "fanart editors update fanart" on public.fanart_entries;
create policy "fanart editors update fanart"
on public.fanart_entries
for update
to authenticated
using (public.is_fanart_editor())
with check (public.is_fanart_editor());

-- Fanart editors can delete fanart
drop policy if exists "fanart editors delete fanart" on public.fanart_entries;
create policy "fanart editors delete fanart"
on public.fanart_entries
for delete
to authenticated
using (public.is_fanart_editor());

-- ============================================================================
-- Bug Reports Policies
-- ============================================================================
alter table public.bug_reports enable row level security;

-- Public can read bug reports (for viewing resolved issues)
drop policy if exists "public read bug reports" on public.bug_reports;
create policy "public read bug reports"
on public.bug_reports
for select
to anon, authenticated
using (true);

-- Anyone can insert bug reports (public submission)
drop policy if exists "public insert bug reports" on public.bug_reports;
create policy "public insert bug reports"
on public.bug_reports
for insert
to anon, authenticated
with check (true);

-- Admins can update bug reports (mark as resolved)
drop policy if exists "admins update bug reports" on public.bug_reports;
create policy "admins update bug reports"
on public.bug_reports
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- Admins can delete bug reports
drop policy if exists "admins delete bug reports" on public.bug_reports;
create policy "admins delete bug reports"
on public.bug_reports
for delete
to authenticated
using (public.is_admin());

-- ---------------------------------------------------------------------------
-- EMAIL-PRIVACY VIEWS — these are what the client (and the public) reads.
-- changed_by_email is NULLed unless the requester is owner/admin. The view
-- runs current_admin_role() (SECURITY DEFINER) per row.
-- ---------------------------------------------------------------------------
create or replace view public.value_change_log_public as
  select
    id, slug, kind, old_value, new_value, changed_by, changed_at,
    case when public.is_owner()
         then changed_by_email
         else null
    end as changed_by_email
  from public.value_change_log;

create or replace view public.wiki_change_log_public as
  select
    id, slug, old_value, new_value, changed_by, changed_at,
    case when public.is_owner()
         then changed_by_email
         else null
    end as changed_by_email
  from public.wiki_change_log;

grant select on public.value_change_log_public to anon, authenticated;
grant select on public.wiki_change_log_public to anon, authenticated;
revoke select on public.value_change_log from anon;
revoke select on public.wiki_change_log from anon;

-- ---------------------------------------------------------------------------
-- Storage: unit-images bucket (images uploaded here, NOT as data URLs in DB)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('unit-images', 'unit-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read unit images" on storage.objects;
create policy "public read unit images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'unit-images');

drop policy if exists "wiki editors upload unit images" on storage.objects;
create policy "wiki editors upload unit images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'unit-images' and public.is_wiki_editor());

drop policy if exists "wiki editors update unit images" on storage.objects;
create policy "wiki editors update unit images"
on storage.objects
for update
to authenticated
using (bucket_id = 'unit-images' and public.is_wiki_editor())
with check (bucket_id = 'unit-images' and public.is_wiki_editor());

drop policy if exists "wiki editors delete unit images" on storage.objects;
create policy "wiki editors delete unit images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'unit-images' and public.is_wiki_editor());

-- ---------------------------------------------------------------------------
-- Realtime publication: required for cross-browser instant live updates.
-- Safe to run repeatedly; only adds tables that are not already published.
--
-- REPLICA IDENTITY FULL is required so DELETE realtime events include the
-- full old row (by default only the primary key is sent, which means 'slug'
-- would be NULL and deletions would silently fail to propagate to visitors).
-- ---------------------------------------------------------------------------
alter table public.value_entries replica identity full;
alter table public.unit_wiki_overrides replica identity full;
alter table public.fanart_entries replica identity full;
alter table public.bug_reports replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'value_entries'
  ) then
    alter publication supabase_realtime add table public.value_entries;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'unit_wiki_overrides'
  ) then
    alter publication supabase_realtime add table public.unit_wiki_overrides;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'fanart_entries'
  ) then
    alter publication supabase_realtime add table public.fanart_entries;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'bug_reports'
  ) then
    alter publication supabase_realtime add table public.bug_reports;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- Recommended Auth settings (Dashboard → Authentication → URL Configuration)
--   Site URL:
--     https://zenithvalues.github.io/<your-repo-name>/
--   Redirect URLs (clean URLs — no hash fragments needed):
--     https://zenithvalues.github.io/<your-repo-name>/
--     https://zenithvalues.github.io/<your-repo-name>/admin
--     https://zenithvalues.github.io/<your-repo-name>/admin/reset-password
--     http://localhost:5173/
--     http://localhost:5173/admin
--     http://localhost:5173/admin/reset-password
-- ---------------------------------------------------------------------------
