-- ============================================================================
-- APEX Values & Wiki — Supabase schema (Expanded Role Hierarchy Revision)
-- Roles: owner, admin_plus, admin, lead_value_editor, lead_wiki_editor, value_editor, wiki_editor, fanart_editor, editor
-- ============================================================================

create table if not exists public.admin_users (
  email text primary key,
  role text not null default 'wiki_editor',
  created_at timestamptz not null default now()
);

alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users add constraint admin_users_role_check
  check (role in ('owner', 'admin_plus', 'admin', 'lead_value_editor', 'lead_wiki_editor', 'value_editor', 'wiki_editor', 'fanart_editor', 'editor'));

create table if not exists public.value_entries (
  slug text primary key,
  kind text not null default 'unit',
  base_value numeric not null default 1,
  gems numeric not null default 1,
  coins numeric not null default 1,
  demand text not null default 'Normal',
  scarcity text not null default 'Standard',
  trend text not null default 'stable',
  notes text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.value_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  kind text not null default 'unit',
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

create table if not exists public.unit_wiki_overrides (
  slug text primary key,
  name text,
  rarity text,
  custom_unit boolean not null default false,
  image_url text,
  description text,
  type text,
  raw_type text,
  category text,
  placement_limit text,
  total_cost text,
  early_game_rank numeric,
  late_game_rank numeric,
  obtain jsonb,
  passive text,
  ability text,
  synergy text,
  min_max_stats jsonb,
  upgrades jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.wiki_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

create table if not exists public.fanart_entries (
  id bigint generated by default as identity primary key,
  title text not null,
  artist_name text not null,
  image_url text not null,
  description text,
  approved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.bug_reports (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text not null,
  page_url text,
  contact text,
  browser text,
  resolved boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.site_announcements (
  id bigint generated by default as identity primary key,
  message text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.admin_users (email, role) values
  ('gustavo.rb1410@gmail.com', 'owner'),
  ('bananatempest25@gmail.com', 'editor'),
  ('destroyha3@gmail.com', 'lead_value_editor'),
  ('hellfiregamingytt@gmail.com', 'value_editor'),
  ('hungryaistukas@gmail.com', 'value_editor'),
  ('luquitas290414@gmail.com', 'lead_wiki_editor'),
  ('treymurphy3rd@gmail.com', 'value_editor')
on conflict (email) do update set role = excluded.role;

create or replace function public.current_admin_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select au.role
  from public.admin_users au
  where lower(au.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1;
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin_plus', 'admin');
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() is not null;
$$;

create or replace function public.is_value_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin_plus', 'admin', 'lead_value_editor', 'lead_wiki_editor', 'value_editor', 'editor');
$$;

create or replace function public.is_wiki_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin_plus', 'admin', 'lead_value_editor', 'lead_wiki_editor', 'wiki_editor', 'editor');
$$;

create or replace function public.is_fanart_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_admin_role() in ('owner', 'admin_plus', 'admin', 'fanart_editor', 'editor');
$$;

create or replace function public.enforce_change_log_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  NEW.changed_by := auth.uid();
  NEW.changed_by_email := lower(coalesce(auth.jwt() ->> 'email', ''));
  return NEW;
end;
$$;

drop trigger if exists trg_value_log_author on public.value_change_log;
create trigger trg_value_log_author
before insert on public.value_change_log
for each row execute function public.enforce_change_log_author();

drop trigger if exists trg_wiki_log_author on public.wiki_change_log;
create trigger trg_wiki_log_author
before insert on public.wiki_change_log
for each row execute function public.enforce_change_log_author();

alter table public.admin_users enable row level security;
alter table public.value_entries enable row level security;
alter table public.value_change_log enable row level security;
alter table public.unit_wiki_overrides enable row level security;
alter table public.wiki_change_log enable row level security;
alter table public.fanart_entries enable row level security;
alter table public.bug_reports enable row level security;
alter table public.site_announcements enable row level security;

drop policy if exists "public read site announcements" on public.site_announcements;
create policy "public read site announcements" on public.site_announcements for select to anon, authenticated using (true);

drop policy if exists "admins insert site announcements" on public.site_announcements;
create policy "admins insert site announcements" on public.site_announcements for insert to authenticated with check (public.is_admin());

drop policy if exists "read own admin role" on public.admin_users;
create policy "read own admin role" on public.admin_users for select to authenticated using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "public read values" on public.value_entries;
create policy "public read values" on public.value_entries for select to anon, authenticated using (true);
drop policy if exists "editors insert values" on public.value_entries;
create policy "editors insert values" on public.value_entries for insert to authenticated with check (public.is_value_editor());
drop policy if exists "editors update values" on public.value_entries;
create policy "editors update values" on public.value_entries for update to authenticated using (public.is_value_editor()) with check (public.is_value_editor());
drop policy if exists "editors delete values" on public.value_entries;
create policy "editors delete values" on public.value_entries for delete to authenticated using (public.is_value_editor());

drop policy if exists "admins read value logs" on public.value_change_log;
create policy "admins read value logs" on public.value_change_log for select to authenticated using (public.is_admin());
drop policy if exists "editors insert value logs" on public.value_change_log;
create policy "editors insert value logs" on public.value_change_log for insert to authenticated with check (public.is_value_editor());

drop policy if exists "public read wiki overrides" on public.unit_wiki_overrides;
create policy "public read wiki overrides" on public.unit_wiki_overrides for select to anon, authenticated using (true);
drop policy if exists "wiki editors insert overrides" on public.unit_wiki_overrides;
create policy "wiki editors insert overrides" on public.unit_wiki_overrides for insert to authenticated with check (public.is_wiki_editor());
drop policy if exists "wiki editors update overrides" on public.unit_wiki_overrides;
create policy "wiki editors update overrides" on public.unit_wiki_overrides for update to authenticated using (public.is_wiki_editor()) with check (public.is_wiki_editor());
drop policy if exists "wiki editors delete overrides" on public.unit_wiki_overrides;
create policy "wiki editors delete overrides" on public.unit_wiki_overrides for delete to authenticated using (public.is_wiki_editor());

drop policy if exists "admins read wiki logs" on public.wiki_change_log;
create policy "admins read wiki logs" on public.wiki_change_log for select to authenticated using (public.is_admin());
drop policy if exists "wiki editors insert logs" on public.wiki_change_log;
create policy "wiki editors insert logs" on public.wiki_change_log for insert to authenticated with check (public.is_wiki_editor());

create or replace view public.value_change_log_public as
  select id, slug, kind, old_value, new_value, changed_by, changed_at,
    case when public.is_owner() then changed_by_email else null end as changed_by_email
  from public.value_change_log;

create or replace view public.wiki_change_log_public as
  select id, slug, old_value, new_value, changed_by, changed_at,
    case when public.is_owner() then changed_by_email else null end as changed_by_email
  from public.wiki_change_log;

grant select on public.value_change_log_public to anon, authenticated;
grant select on public.wiki_change_log_public to anon, authenticated;

alter table public.value_entries replica identity full;
alter table public.unit_wiki_overrides replica identity full;
alter table public.site_announcements replica identity full;

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'value_entries') then
    alter publication supabase_realtime add table public.value_entries;
  end if;

  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'unit_wiki_overrides') then
    alter publication supabase_realtime add table public.unit_wiki_overrides;
  end if;

  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'site_announcements') then
    alter publication supabase_realtime add table public.site_announcements;
  end if;
end $$;
