-- APEX Values & Wiki Supabase setup
-- Run this in Supabase SQL Editor.
-- Project: https://rfeoicbcprziqlcmbjgi.supabase.co

create table if not exists public.admin_users (
  email text primary key,
  role text not null default 'wiki_editor',
  created_at timestamptz not null default now()
);

-- Expand older role constraint if it exists.
alter table public.admin_users drop constraint if exists admin_users_role_check;
alter table public.admin_users add constraint admin_users_role_check
  check (role in ('owner', 'admin', 'value_editor', 'wiki_editor', 'editor'));

insert into public.admin_users (email, role) values
  ('gustavo.rb1410@gmail.com', 'owner'),
  ('bananatempest25@gmail.com', 'editor'),
  ('destroyha3@gmail.com', 'value_editor'),
  ('hellfiregamingytt@gmail.com', 'value_editor'),
  ('hungryaistukas@gmail.com', 'value_editor'),
  ('luquitas290414@gmail.com', 'wiki_editor'),
  ('treymurphy3rd@gmail.com', 'value_editor')
on conflict (email) do update set role = excluded.role;

create table if not exists public.value_entries (
  slug text primary key,
  kind text not null default 'unit',
  base_value numeric not null default 1,
  gems numeric not null default 1,
  coins numeric not null default 1,
  demand text not null default 'Normal',
  scarcity text not null default 'Standard',
  trend text not null default 'stable',
  notes text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.value_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  kind text not null default 'unit',
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

create table if not exists public.unit_wiki_overrides (
  slug text primary key,
  name text,
  rarity text,
  custom_unit boolean not null default false,
  image_url text,
  description text,
  type text,
  raw_type text,
  category text,
  placement_limit text,
  total_cost text,
  early_game_rank numeric,
  late_game_rank numeric,
  obtain jsonb,
  passive text,
  ability text,
  synergy text,
  min_max_stats jsonb,
  upgrades jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.wiki_change_log (
  id bigint generated by default as identity primary key,
  slug text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_by_email text,
  changed_at timestamptz not null default now()
);

alter table public.value_change_log add column if not exists changed_by_email text;
alter table public.wiki_change_log add column if not exists changed_by_email text;
alter table public.unit_wiki_overrides add column if not exists name text;
alter table public.unit_wiki_overrides add column if not exists rarity text;
alter table public.unit_wiki_overrides add column if not exists custom_unit boolean not null default false;
alter table public.unit_wiki_overrides add column if not exists early_game_rank numeric;
alter table public.unit_wiki_overrides add column if not exists late_game_rank numeric;

alter table public.admin_users enable row level security;
alter table public.value_entries enable row level security;
alter table public.value_change_log enable row level security;
alter table public.unit_wiki_overrides enable row level security;
alter table public.wiki_change_log enable row level security;

create or replace function public.is_value_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where lower(au.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and au.role in ('owner', 'admin', 'value_editor', 'editor')
  );
$$;

create or replace function public.is_wiki_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users au
    where lower(au.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and au.role in ('owner', 'admin', 'wiki_editor', 'editor')
  );
$$;

-- Admin roles: logged-in users can read their own role.
drop policy if exists "read own admin role" on public.admin_users;
create policy "read own admin role"
on public.admin_users
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- Public site can read values.
drop policy if exists "public read values" on public.value_entries;
create policy "public read values"
on public.value_entries
for select
to anon, authenticated
using (true);

-- Permissioned value editors can insert/update/delete values.
drop policy if exists "editors insert values" on public.value_entries;
create policy "editors insert values"
on public.value_entries
for insert
to authenticated
with check (public.is_value_editor());

drop policy if exists "editors update values" on public.value_entries;
create policy "editors update values"
on public.value_entries
for update
to authenticated
using (public.is_value_editor())
with check (public.is_value_editor());

drop policy if exists "editors delete values" on public.value_entries;
create policy "editors delete values"
on public.value_entries
for delete
to authenticated
using (public.is_value_editor());

-- Public can read value logs. Value editors can insert logs.
drop policy if exists "public read value logs" on public.value_change_log;
create policy "public read value logs"
on public.value_change_log
for select
to anon, authenticated
using (true);

drop policy if exists "editors insert value logs" on public.value_change_log;
create policy "editors insert value logs"
on public.value_change_log
for insert
to authenticated
with check (public.is_value_editor());

-- Public can read WIKI overrides. WIKI editors can change them.
drop policy if exists "public read wiki overrides" on public.unit_wiki_overrides;
create policy "public read wiki overrides"
on public.unit_wiki_overrides
for select
to anon, authenticated
using (true);

drop policy if exists "wiki editors insert overrides" on public.unit_wiki_overrides;
create policy "wiki editors insert overrides"
on public.unit_wiki_overrides
for insert
to authenticated
with check (public.is_wiki_editor());

drop policy if exists "wiki editors update overrides" on public.unit_wiki_overrides;
create policy "wiki editors update overrides"
on public.unit_wiki_overrides
for update
to authenticated
using (public.is_wiki_editor())
with check (public.is_wiki_editor());

drop policy if exists "wiki editors delete overrides" on public.unit_wiki_overrides;
create policy "wiki editors delete overrides"
on public.unit_wiki_overrides
for delete
to authenticated
using (public.is_wiki_editor());

-- Public can read WIKI logs. WIKI editors can insert logs.
drop policy if exists "public read wiki logs" on public.wiki_change_log;
create policy "public read wiki logs"
on public.wiki_change_log
for select
to anon, authenticated
using (true);

drop policy if exists "wiki editors insert logs" on public.wiki_change_log;
create policy "wiki editors insert logs"
on public.wiki_change_log
for insert
to authenticated
with check (public.is_wiki_editor());


-- Unit image uploads for WIKI editors.
insert into storage.buckets (id, name, public)
values ('unit-images', 'unit-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read unit images" on storage.objects;
create policy "public read unit images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'unit-images');

drop policy if exists "wiki editors upload unit images" on storage.objects;
create policy "wiki editors upload unit images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'unit-images' and public.is_wiki_editor());

drop policy if exists "wiki editors update unit images" on storage.objects;
create policy "wiki editors update unit images"
on storage.objects
for update
to authenticated
using (bucket_id = 'unit-images' and public.is_wiki_editor())
with check (bucket_id = 'unit-images' and public.is_wiki_editor());

drop policy if exists "wiki editors delete unit images" on storage.objects;
create policy "wiki editors delete unit images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'unit-images' and public.is_wiki_editor());

-- Recommended Auth settings:
-- Authentication > URL Configuration > Site URL:
-- https://zenithvalues.github.io/Apex-Ball-TD-WIKI/
-- Redirect URLs:
-- https://zenithvalues.github.io/Apex-Ball-TD-WIKI/
-- https://zenithvalues.github.io/Apex-Ball-TD-WIKI/#/admin
-- https://zenithvalues.github.io/Apex-Ball-TD-WIKI/#/admin/reset-password
-- http://localhost:5173/
-- http://localhost:5173/#/admin
-- http://localhost:5173/#/admin/reset-password
