#!/usr/bin/env python3
"""
Converts units_parsed.json into a JS module (src/data/generated/units.generated.js)
exporting GENERATED_UNITS: an array of unit objects matching the site's schema,
plus GENERATED_VALUE_OVERRIDES setting every unit's market value to 1 (per request).
"""
import json
import re
import sys

TYPE_KEYWORDS_SUMMONER = ['summon', 'summoner']
TYPE_KEYWORDS_SUPPORT = ['boost', 'booster', 'buff']
TYPE_KEYWORDS_ECONOMY = ['cash', 'income', 'generation']


def classify_type(raw_type):
    if not raw_type:
        return 'DPS'
    t = raw_type.lower()
    if any(k in t for k in TYPE_KEYWORDS_SUMMONER):
        return 'Summoner'
    if any(k in t for k in TYPE_KEYWORDS_SUPPORT):
        return 'Support'
    if any(k in t for k in TYPE_KEYWORDS_ECONOMY):
        return 'Economy'
    return 'DPS'


def js_string(s):
    return json.dumps(s, ensure_ascii=False)


def js_value(v):
    """Convert a python value to a JS literal string."""
    if v is None:
        return 'null'
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if isinstance(v, (int, float)):
        return json.dumps(v)
    if isinstance(v, str):
        return js_string(v)
    if isinstance(v, list):
        return '[' + ', '.join(js_value(x) for x in v) + ']'
    if isinstance(v, dict):
        parts = []
        for k, val in v.items():
            key = k if re.match(r'^[A-Za-z_$][A-Za-z0-9_$]*$', k) else js_string(k)
            parts.append(f'{key}: {js_value(val)}')
        return '{ ' + ', '.join(parts) + ' }'
    return 'null'


def main():
    infile = sys.argv[1] if len(sys.argv) > 1 else 'src/data/raw/units_parsed.json'
    outfile = sys.argv[2] if len(sys.argv) > 2 else 'src/data/generated/units.generated.js'

    data = json.load(open(infile, encoding='utf-8'))

    units = []
    for d in data:
        unit_type = classify_type(d.get('type'))
        category = d['categories'][0] if d.get('categories') else 'Standard'
        # if multiple categories, prefer the more specific non-Standard tag
        non_standard = [c for c in d.get('categories', []) if c != 'Standard']
        if non_standard:
            category = non_standard[0]

        upgrades = []
        for u in d.get('upgrades', []):
            upgrades.append({
                'level': u['level'],
                'label': u['label'],
                'cost': u.get('cost'),
                'costRaw': u.get('costRaw'),
                'description': u.get('description'),
                'cooldown': u.get('cooldown'),
                'range': u.get('range'),
                'attacks': u.get('attacks') or {},
                'dps': u.get('dps') or {},
            })

        units.append({
            'slug': d['slug'],
            'name': d['name'],
            'rarity': d['rarity'],
            'type': unit_type,
            'rawType': d.get('type'),
            'category': category,
            'categories': d.get('categories', []),
            'placementLimit': d.get('placementLimit'),
            'obtain': d.get('obtain', []),
            'passive': d.get('passive'),
            'ability': d.get('ability'),
            'synergy': d.get('synergy'),
            'unavailableData': d.get('unavailableData', False),
            'upgrades': upgrades,
            'minMaxStats': d.get('minMaxStats', {}),
            'documented': not d.get('unavailableData', False),
        })

    lines = []
    lines.append('// AUTO-GENERATED by scripts/build_units_js.py — do not hand-edit.')
    lines.append('// Source: "Ball TD Units stat sheet.txt" (community stat sheet).')
    lines.append('// Regenerate with: python3 scripts/parse_units.py && python3 scripts/build_units_js.py')
    lines.append('')
    lines.append('export const GENERATED_UNITS = [')
    for u in units:
        lines.append('  ' + js_value(u) + ',')
    lines.append('];')
    lines.append('')
    lines.append('// Every unit\'s market value set to 1 per current instruction.')
    lines.append('// slug -> { baseValue, demand, scarcity }')
    lines.append('export const GENERATED_VALUE_OVERRIDES = {')
    for u in units:
        if u['unavailableData']:
            continue
        lines.append(f"  {js_string(u['slug'])}: {{ baseValue: 1, demand: 'Normal', scarcity: 'Standard' }},")
    lines.append('};')
    lines.append('')

    with open(outfile, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {len(units)} units to {outfile}', file=sys.stderr)


if __name__ == '__main__':
    main()
