#!/usr/bin/env python3
"""
Converts units_parsed.json into a JS module exporting GENERATED_UNITS plus
GENERATED_VALUE_OVERRIDES.

Usage: python3 scripts/build_units_js.py <input.json> <output.js>
"""
import json
import sys

TYPE_KEYWORDS_SUMMONER = ['summon', 'summoner', 'cloning']
TYPE_KEYWORDS_SUPPORT = ['boost', 'booster', 'buff']
TYPE_KEYWORDS_ECONOMY = ['cash', 'income', 'generation', 'coin', 'money']


def classify_type(raw_type):
    if not raw_type:
        return 'DPS'
    t = raw_type.lower()
    if any(k in t for k in TYPE_KEYWORDS_SUMMONER):
        return 'Summoner'
    if any(k in t for k in TYPE_KEYWORDS_SUPPORT):
        return 'Support'
    if any(k in t for k in TYPE_KEYWORDS_ECONOMY):
        return 'Economy'
    return 'DPS'


def compact_upgrade(upgrade):
    return {
        'level': upgrade.get('level'),
        'label': upgrade.get('label'),
        'isMax': upgrade.get('isMax', False),
        'cost': upgrade.get('cost'),
        'costRaw': upgrade.get('costRaw'),
        'description': upgrade.get('description'),
        'cooldown': upgrade.get('cooldown'),
        'range': upgrade.get('range'),
        'stats': upgrade.get('stats') or {},
        'attacks': upgrade.get('attacks') or {},
        'dps': upgrade.get('dps') or {},
        'costPerDps': upgrade.get('costPerDps'),
    }


def main():
    infile = sys.argv[1] if len(sys.argv) > 1 else 'scripts/raw/units_parsed.json'
    outfile = sys.argv[2] if len(sys.argv) > 2 else 'src/data/generated/units.generated.js'

    data = json.load(open(infile, encoding='utf-8'))

    units = []
    for d in data:
        categories = d.get('categories') or []
        category = categories[0] if categories else 'Standard'
        non_standard = [c for c in categories if c != 'Standard']
        if non_standard:
            category = non_standard[0]

        upgrades = [compact_upgrade(u) for u in d.get('upgrades', [])]

        units.append({
            'slug': d['slug'],
            'name': d['name'],
            'rarity': d['rarity'],
            'type': classify_type(d.get('type')),
            'rawType': d.get('type'),
            'category': category,
            'categories': categories,
            'valueRaw': d.get('valueRaw'),
            'coinsRaw': d.get('coinsRaw'),
            'gemsRaw': d.get('gemsRaw'),
            'placementLimit': d.get('placementLimit'),
            'totalCost': d.get('totalCost'),
            'obtain': d.get('obtain', []),
            'passive': d.get('passive'),
            'ability': d.get('ability'),
            'synergy': d.get('synergy'),
            'unavailableData': d.get('unavailableData', False),
            'upgrades': upgrades,
            'upgradeCount': max(len(upgrades) - 1, 0) if upgrades else 0,
            'minMaxStats': d.get('minMaxStats', {}),
            'documented': not d.get('unavailableData', False),
        })

    value_overrides = {
        u['slug']: {'baseValue': 1, 'demand': 'Normal', 'scarcity': 'Standard'}
        for u in units
        if not u.get('unavailableData')
    }

    lines = []
    lines.append('// AUTO-GENERATED by scripts/build_units_js.py — do not hand-edit.')
    lines.append('// Source: "Ball TD Units stat sheet.txt" (community stat sheet).')
    lines.append('// Regenerate with:')
    lines.append('//   python3 scripts/parse_units.py "Ball TD Units stat sheet.txt" scripts/raw/units_parsed.json')
    lines.append('//   python3 scripts/build_units_js.py scripts/raw/units_parsed.json src/data/generated/units.generated.js')
    lines.append(f'// Total: {len(units)} units; {sum(len(u["upgrades"]) for u in units)} upgrade/placement rows.')
    lines.append('')
    lines.append('export const GENERATED_UNITS = ' + json.dumps(units, ensure_ascii=False, indent=2) + ';')
    lines.append('')
    lines.append('// Every unit\'s market value is set to 1 per current instruction.')
    lines.append('// slug -> { baseValue, demand, scarcity }')
    lines.append('export const GENERATED_VALUE_OVERRIDES = ' + json.dumps(value_overrides, ensure_ascii=False, indent=2) + ';')
    lines.append('')

    with open(outfile, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f'Wrote {len(units)} units to {outfile}', file=sys.stderr)
    print(f'Upgrade/placement rows: {sum(len(u["upgrades"]) for u in units)}', file=sys.stderr)


if __name__ == '__main__':
    main()
